site_name: 基于seq2seq模型的自然语言处理应用
site_author: 徐静
site_favicon: icon.ico
repo_url: https://github.com/DataXujing/seq2seqlearn/
pages:
  - 主页: index.md
  - Seq2Seq2简介: chapter1.md
  - Encoder-Decoder结构: chapter2.md
  - seq2seq模型的python实现: chapter3.md
  - 实现文本QA软件: chapter4.md
  - 实现(联信)QA系统的可行性: chapter5.md
  - 关于: about.md
theme: readthedocs
